# Generated by Django 5.2.17 on 2026-10-03 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255, unique=True, verbose_name='Фраза')),
                ('aliases', models.TextField(blank=True, verbose_name='Алиасы (по одному на строке)')),
                ('exclusions', models.TextField(blank=True, verbose_name='Исключающие фразы (по одной на строке)')),
                ('fuzzy', models.BooleanField(default=True, verbose_name='Учитывать опечатки')),
                ('enabled', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Ключевое слово / фраза',
                'verbose_name_plural': 'Ключевые слова / фразы',
                'ordering': ['phrase'],
            },
        ),
        migrations.CreateModel(
            name='SourceChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('locator', models.CharField(max_length=500, unique=True, verbose_name='ID, @username или ссылка')),
                ('chat_id', models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='Telegram ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Сканировать')),
                ('last_error', models.TextField(blank=True, editable=False, verbose_name='Ошибка подключения')),
                ('resolved_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Проверено')),
            ],
            options={
                'verbose_name': 'Исходный чат',
                'verbose_name_plural': 'Исходные чаты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TargetChat',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Моя группа', max_length=255, verbose_name='Название')),
                ('locator', models.CharField(max_length=500, verbose_name='ID, @username или ссылка')),
                ('chat_id', models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='Telegram ID')),
                ('last_error', models.TextField(blank=True, editable=False, verbose_name='Ошибка подключения')),
                ('resolved_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Проверено')),
            ],
            options={
                'verbose_name': 'Целевая группа',
                'verbose_name_plural': 'Целевая группа',
            },
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('encrypted_session', models.TextField(blank=True, editable=False, verbose_name='Зашифрованная сессия')),
                ('pending_session', models.TextField(blank=True, editable=False, verbose_name='Ожидающая сессия')),
                ('pending_phone_hash', models.CharField(blank=True, editable=False, max_length=255, verbose_name='Хеш кода')),
                ('pending_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Код запрошен')),
                ('pending_requires_password', models.BooleanField(default=False, editable=False, verbose_name='Нужен пароль 2FA')),
                ('connected_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Подключен')),
            ],
            options={
                'verbose_name': 'Telegram-аккаунт',
                'verbose_name_plural': 'Telegram-аккаунт',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_chat_id', models.BigIntegerField(verbose_name='ID исходного чата')),
                ('message_id', models.BigIntegerField(verbose_name='ID сообщения')),
                ('target_chat_id', models.BigIntegerField(verbose_name='ID целевой группы')),
                ('preview', models.TextField(blank=True, verbose_name='Текст')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Переслано'), ('failed', 'Ошибка')], default='pending', max_length=12, verbose_name='Статус')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попытки')),
                ('last_error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Переслано')),
                ('keyword', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.keyword', verbose_name='Правило')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scanner.sourcechat', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Пересылка',
                'verbose_name_plural': 'Журнал пересылок',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('source_chat_id', 'message_id', 'target_chat_id'), name='unique_delivery')],
            },
        ),
    ]
