# Generated by Django 5.2.17 on 2026-10-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcechat',
            options={'ordering': ['title'], 'verbose_name': 'Группа или канал-источник', 'verbose_name_plural': 'Группы и каналы-источники'},
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='pending_qr_error',
            field=models.TextField(blank=True, editable=False, verbose_name='Ошибка QR'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='pending_qr_expires_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='QR действителен до'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='pending_qr_id',
            field=models.CharField(blank=True, editable=False, max_length=36, verbose_name='Запрос QR'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='pending_qr_url',
            field=models.TextField(blank=True, editable=False, verbose_name='QR-ссылка'),
        ),
    ]
