# Generated by Django 5.2.17 on 2026-10-03 16:11

from django.db import migrations, models


def create_default_format(apps, schema_editor):
    apps.get_model('scanner', 'MessageFormat').objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_alter_sourcechat_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFormat',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('template', models.TextField(default='{text}\n\n{contact}', help_text='Поля: {text}, {contact}, {source}, {keyword}. {text} и {contact} нужны по одному разу.', verbose_name='Шаблон сообщения')),
                ('contact_label', models.CharField(default='Написать в личку', max_length=80, verbose_name='Текст ссылки на автора')),
                ('channel_label', models.CharField(default='Открыть публикацию', max_length=80, verbose_name='Текст ссылки на канал')),
            ],
            options={
                'verbose_name': 'Формат сообщения',
                'verbose_name_plural': 'Формат сообщений',
            },
        ),
        migrations.RunPython(create_default_format, migrations.RunPython.noop),
    ]
