# Generated by Django 5.2.17 on 2026-10-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_messageformat'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageformat',
            name='show_origin',
            field=models.BooleanField(default=False, help_text='Добавляет строку с названием группы или канала в то же сообщение.', verbose_name='Показывать источник сообщения'),
        ),
    ]
